version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: nestjs-app-dev
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USERNAME=ukseung
      - DB_PASSWORD=flqqka!#%24
      - DB_DATABASE=TestDB
      - NODE_ENV=development
    command: npm run start:dev
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    networks:
      - nestjs-network

  mysql:
    image: mysql:8.4.5
    container_name: nestjs-mysql-dev
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ukseung
      MYSQL_PASSWORD: flqqka!#%24
      MYSQL_DATABASE: TestDB
    volumes:
      - mysql-dev-data:/var/lib/mysql
    networks:
      - nestjs-network

networks:
  nestjs-network:
    name: nestjs-network-dev

volumes:
  mysql-dev-data: 